version: "3"

services: 
  api:
    build: api
    ports:
      - "3000:3000"
    depends_on:
      - db 
    networks:
      - redis_network

  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge
